### ISSUE TITLE
Amazon Delivered Typo

### ISSUE THREAD

**Issue by julianrinaldi** [moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card#25]
**Describe the bug**
"Delivered" is spelled wrong on the Amazon Delivered sensor

<img width="469" alt="CleanShot 2021-03-22 at 07 22 21@2x" src="https://user-images.githubusercontent.com/492435/111982587-86de7c80-8adf-11eb-8db2-fe621cb21a77.png">

**Comment by moralmunky** [comment]
Thanks for the catch! Fixed in v0.7.2.3.

**Comment by julianrinaldi** [comment]
I think you may have missed it, or there was another misspelling. It's still misspelled on the card, and I can still see it misspelled in the code for v0.7.2.3.
